### ISSUE TITLE
Types in Output of Options

### ISSUE THREAD

**Issue by swojit** [lukeed/sade#19]
I couldn't find any way to display/specify which types arguments take in. For instance, something like this would be helpful.
```
$ my-cli --help

  Options
    -c, --config     Provide path to custom config  (default foo.config.js) [Type: String]
```

**Comment by lukeed** [comment]
Hey~! 

Because it's `argv`, everything is entered as a string; `mri` then casts the value to boolean or number types if it can be inferred or if you've passed along the custom `parse()` options to do so.

The only other input form that Sade (and most) accepts is repetitive flag instances construct an array.

So:

```sh
$ foo --bar 123
#=> bar: 123 (number, inferred)

$ foo --bar
#=> bar: true (boolean, inferred)

$ foo --bar baz
#=> bar: "baz" (string, default)

$ foo --bar baz --bar 123
#=> bar: ["baz", 123]
```

**Comment by swojit** [comment]
I see. But is there a way to display what type an argument takes in, to the user?

**Comment by lukeed** [comment]
Nope, sorry. Again, because it only _takes in_ strings. Only the program will see what it's been inferred as/casted as.

**Comment by swojit** [comment]
Thanks for the quick responses! Imo it would be cool if this was a feature!

**Comment by lukeed** [comment]
No problem :)
