### ISSUE TITLE
Is it possible to use 'generic' value as the default command?

### ISSUE THREAD

**Issue by djalmaaraujo** [lukeed/sade#2]
Let me try to explain.

I have this CLI:

```bash
my-cli something-else
```

```bash
my-cli -h
```

I want to be able to use what I want as the first argument. Something like this:

```js
// Instead of:
.command('build <entry>')
// just:
.command('<entry>')
```

is that clear?

A more real example:

```js
prog
    .command('<entry>')
    .describe('List your entries')
    .option('a, --add')
    .action((entry, opts) => {
      console.log('You said:')
      console.log(entry)
     })
```

I need to be able to run `my-cli hello` and not only using `my-cli a hello`

**Comment by lukeed** [comment]
Hey~!

For now, I think your safest bet is to just define a default command.

Another, more hacky (and less reliable solution) is to edit the `prog` instance directly to do what you want. I don't recommend this, as things will mostly likely change going forward.

```js
const prog = sade('foo');
const KEY = '__default__';

// mutate internals, without method calls
prog.default = prog.curr = KEY; // set default & current cmd for methods' state
prog.tree[KEY].usage = '<entry>' ; // override usage pattern

prog // still referencing KEY
  .option('-a, --add', 'Description for flag')
  .action((entry, opts) => {
    // ...
  });

prog.parse(process.argv.concat('')); //=> important!
```

I'll have to think about whether or not I want to support this pattern. IMO you don't really have a CLI until you have multiple commands.

Hope that helps~!

**Comment by djalmaaraujo** [comment]
@lukeed The thing here is not that I don't have multiple commands. It's more like a shortcut. I am building a cli that the most used shortcut would be something like `cli x texttt...`, but for faster usage, would be nice to just `cli texttt`.

**Comment by lukeed** [comment]
Okay, thanks for the feedback 😄 

Try the above & lemme know how it goes. I did a quick test script & it allows your `cli texttt` example, with flags.

**Comment by djalmaaraujo** [comment]
@lukeed This is the repo in question. https://github.com/djalmaaraujo/WrK. I will add your solution ASAP and let you know. :)

**Comment by olstenlarck** [comment]
Hey @lukeed! :)

It's not related to that issues, but it is close to the suggested solution.
How can make that instead of `Insufficient arguments!` to output the help when there is no commands.

Forgot above. Just figured it out. It's again hacky, but I definitely will propose change for that case.

So the trick for when you want single command to be default

```js
const cli = Sade()

// use another key, different than the `__default__`
cli.default = cli.curr = '__DEF__';

// shallow copy, intentionally
cli.tree.__DEF__ = Object.assign({}, cli.tree.__default__);

cli.tree.__DEF__.usage = '';
cli.tree.__DEF__.handler = async () => cli.help();
```

**Comment by olstenlarck** [comment]
That's how i called it for third party users :D 

![2018-05-17-05 28 54_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/40153650-6852d91c-5993-11e8-840b-b566e4f951e7.png)

So later the user will use it and pass a function that will be called, for example `prog.help()`

```js
const prog = sade()

prog.commandless(() => prog.help())

// ... another commands
```

**Comment by lukeed** [comment]
Yo~!

This has been on my internal TODOs recently. Going to extract a `run()` proto and then add some option hooks that effectively act as event listeners. The current behavior(s) will be maintained as the defaults, but the hooks will allow for easy customizations.

They'll solve @djalmaaraujo's request for single-command-mode here (and #16) and @olstenlarck's desire for help-by-default, which is the ***complete*** opposite behavior.

I can't get to it quite yet, but I will soon. I'll need to test thoroughly across the various business-facing apps I have before publishing a `1.5.0` 👍

**Comment by olstenlarck** [comment]
I was going to suggest easy fix for cases like my scenario, around those lines

https://github.com/lukeed/sade/blob/master/lib/index.js#L128-L130

So if `opts.noCommand` is passed to the `.parse` options and it is a function, call it, otherwise output the current error message.

Here now came one more thing: allow passing options throught the `sade()` as second argument, and object.assign them with those passed to the `.parse` method.

**Comment by lukeed** [comment]
Yes, for your case, those lines are relevant. It's just going to be a matter of segmenting the current `parse()` while preserving logic.

Yes, hooks will be a second argument to `sade()`. No extending with/from `parse` though; completely separate. "Global" options change the behavior of the application as a whole. Parse options are instance-specific, and must hve the ability to change between calls. This is why `parse` is callable method.

**Comment by olstenlarck** [comment]
Cool for the hooks.

Huh, there is use cases when you call `.parse` more than once? Why? I don't believe. :D

**Comment by olstenlarck** [comment]
Ahh yea.. my cases are endless :rofl: Actually, i always just think for edge cases, users are pretty wild some time. So while developing i'm testing anything that i can think of.

So one more case from me: Because i'm depending on that that `parse` returns an object (because of the `lazy: true` option) i end with errors that i the result of it is `undefined`. And the cases when it returns undefined is few:
- when lazy is false and handler given on `.action` returns nothing
- when there is no specified command AND `--help` or `--version` flags are given

For example

```js
$ mycli not-existing --help
```

It should not end with some weird errors, but with the more friendlier `No specified command`. The reason that this output isn't shown is because the `if`s for `argv.version` and `argv.help` are before the `cmd === void 0`.

So the fix is to move them after that and upgrade that "if cmd void".

```js
if ((argv.help || argv.version) && cmd === void 0) {
  // argv._[0] is the only way to get the real command at that phase?
  return $.error(bin, `No "${argv._[0]}" command specified.`);
}

if (argv.version) {
  return console.log(`${bin}, ${this.ver}`);
}

if (argv.help) {
  return this.help(!isVoid && name);
}
```

so now it outputs good error

```
❯ node -r esm ./cli lint --version

  ERROR
    No "lint" command specified.

  Run `$ hela --help` for more info.
```

**Comment by galvez** [comment]
My solution to this problem:

```js
const makeDefault = (argv, defaultCommand) => {
  argv = [ ...argv ]
  argv.splice(2, 0, 'defaultCommand')
  return argv
}

prog.parse(injectArgv(process.argv, 'myDefaultCommand'))
```

**Comment by galvez** [comment]
Heh, ended up migrating to https://github.com/tj/commander.js/

It has variadic arguments. Didn't mess up with my CLI help text. Nice.
