### ISSUE TITLE
benefits to use sade over all the other "100" libs?

### ISSUE THREAD

**Issue by soenkekluth** [lukeed/sade#3]
what would you say makes sade the right way?

**Comment by lukeed** [comment]
Hey! I don't think there is a "right" way at all. Obviously all the solutions out there work and have their own flare, whether it's a "nicer" API, extra features baked in, or XYZ.

I made this because I only use `mri` these days and wanted a reusable convenience layer that parsed/handled commands and generated nicely formatted help output for me. I was manually doing it a few times, which meant it was time to extract :D

That said, it's my personal opinion that Sade has really nice help output & its API methods are clear and simple. Of course, I wrote it & this is how I write CLIs anyway -- you may not like it at all and that's perfectly fine lol 

Lastly, because this is largely based on `mri`, you can take a look at [its comparisons & benchmarks](https://github.com/lukeed/mri#comparisons) and get more info that way.

Hope that helps!
